version: 2.1
orbs:
  codecov: codecov/codecov@3.1.1
jobs:
  build:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run: go build -v  cmd/manager/main.go
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
          command: |
            go test -coverprofile=c.out ./...
            go tool cover -html=c.out -o coverage.html
            mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
