apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloaks.keycloak.org
spec:
  group: keycloak.org
  names:
    kind: Keycloak
    listKind: KeycloakList
    plural: keycloaks
    singular: keycloak
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Keycloak is the Schema for the keycloaks API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KeycloakSpec defines the desired state of Keycloak.
            properties:
              external:
                description: Contains configuration for external Keycloak instances.
                  Unmanaged needs to be set to true to use this.
                properties:
                  enabled:
                    description: If set to true, this Keycloak will be treated as
                      an external instance. The unmanaged field also needs to be set
                      to true if this field is true.
                    type: boolean
                  url:
                    description: The URL to use for the keycloak admin API. Needs
                      to be set if external is true.
                    type: string
                type: object
              unmanaged:
                default: true
                description: When set to true, this Keycloak will be marked as unmanaged
                  and will not be managed by this operator. It can then be used for
                  targeting purposes.
                type: boolean
            type: object
          status:
            description: KeycloakStatus defines the observed state of Keycloak.
            properties:
              credentialSecret:
                description: The secret where the admin credentials are to be found.
                type: string
              externalURL:
                description: External URL for accessing Keycloak instance from outside
                  the cluster. Is identical to external.URL if it's specified, otherwise
                  is computed (e.g. from Ingress).
                type: string
              message:
                description: Human-readable message indicating details about current
                  operator phase or error.
                type: string
              phase:
                description: Current phase of the operator.
                type: string
              ready:
                description: True if all resources are in a ready state and all work
                  is done.
                type: boolean
              secondaryResources:
                additionalProperties:
                  items:
                    type: string
                  type: array
                description: 'A map of all the secondary resources types and names
                  created for this CR. e.g "Deployment": [ "DeploymentName1", "DeploymentName2"
                  ].'
                type: object
              version:
                description: Version of Keycloak or RHSSO running on the cluster.
                type: string
            required:
            - credentialSecret
            - message
            - phase
            - ready
            - version
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
