apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloakclient-operator
rules:
- apiGroups:
  - ""
  resources:
  - events
  - pods
  - configmaps
  - secrets
  verbs:
  - list
  - get
  - create
  - patch
  - update
  - watch
  - delete
- apiGroups:
  - keycloak.org
  resources:
  - keycloaks
  - keycloaks/status
  - keycloaks/finalizers
  - keycloakrealms
  - keycloakrealms/status
  - keycloakrealms/finalizers
  - keycloakclients
  - keycloakclients/status
  - keycloakclients/finalizers
  verbs:
  - get
  - list
  - update
  - watch
