apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloakclient-operator
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - services/finalizers
      - events
      - secrets
      - configmaps
      - pods
    verbs:
      - list
      - get
      - create
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - apps
    resources:
      - replicasets
      - deployments
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - list
      - get
      - create
      - update
      - watch
  - apiGroups:
      - apps
    resourceNames:
      - keycloak-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
